// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUIMultipleUIMapFiles.Pages_UIMaps.HomePage_UIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class HomePage_UIMap
    {
        
        #region Properties
        public GoogleBrowserWindow GoogleBrowserWindow
        {
            get
            {
                if ((this.mGoogleBrowserWindow == null))
                {
                    this.mGoogleBrowserWindow = new GoogleBrowserWindow();
                }
                return this.mGoogleBrowserWindow;
            }
        }
        #endregion
        
        #region Fields
        private GoogleBrowserWindow mGoogleBrowserWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class GoogleBrowserWindow : BrowserWindow
    {
        
        public GoogleBrowserWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Google", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public GoogleDocument GoogleDocument
        {
            get
            {
                if ((this.mGoogleDocument == null))
                {
                    this.mGoogleDocument = new GoogleDocument(this);
                }
                return this.mGoogleDocument;
            }
        }
        #endregion
        
        #region Fields
        private GoogleDocument mGoogleDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class GoogleDocument : HtmlDocument
    {
        
        public GoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "gsr";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            #endregion
        }
        
        #region Properties
        public HtmlEdit SearchTextBox
        {
            get
            {
                if ((this.mSearchTextBox == null))
                {
                    this.mSearchTextBox = new HtmlEdit(this);
                    #region Search Criteria
                    this.mSearchTextBox.SearchProperties[HtmlEdit.PropertyNames.Id] = "lst-ib";
                    this.mSearchTextBox.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mSearchTextBox.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mSearchTextBox.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mSearchTextBox.FilterProperties[HtmlEdit.PropertyNames.Title] = "Search";
                    this.mSearchTextBox.FilterProperties[HtmlEdit.PropertyNames.Class] = "gsfi lst-d-f";
                    this.mSearchTextBox.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" title=\"Search\" class=\"gsfi lst-";
                    this.mSearchTextBox.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    #endregion
                }
                return this.mSearchTextBox;
            }
        }
        
        public HtmlButton SearchButton
        {
            get
            {
                if ((this.mSearchButton == null))
                {
                    this.mSearchButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mSearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = "btnG";
                    this.mSearchButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "lsb";
                    #endregion
                }
                return this.mSearchButton;
            }
        }
        
        public HtmlHyperlink SignInHyperlink
        {
            get
            {
                if ((this.mSignInHyperlink == null))
                {
                    this.mSignInHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mSignInHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "gb_70";
                    this.mSignInHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sign in";
                    this.mSignInHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "gb_Le gb_Ha gb_vb";
                    #endregion
                }
                return this.mSignInHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mSearchTextBox;
        
        private HtmlButton mSearchButton;
        
        private HtmlHyperlink mSignInHyperlink;
        #endregion
    }
}
