// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUIMultipleUIMapFiles.Pages_UIMaps.SignInPage_UIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class SignInPage_UIMap
    {
        
        #region Properties
        public GoogleAccountSignInWindow GoogleAccountSignInWindow
        {
            get
            {
                if ((this.mGoogleAccountSignInWindow == null))
                {
                    this.mGoogleAccountSignInWindow = new GoogleAccountSignInWindow();
                }
                return this.mGoogleAccountSignInWindow;
            }
        }
        #endregion
        
        #region Fields
        private GoogleAccountSignInWindow mGoogleAccountSignInWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class GoogleAccountSignInWindow : BrowserWindow
    {
        
        public GoogleAccountSignInWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControl.PropertyNames.Name, "Sign in - Google Accounts", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Sign in - Google Accounts");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public GoogleAccountSignInDocument GoogleAccountSignInDocument
        {
            get
            {
                if ((this.mGoogleAccountSignInDocument == null))
                {
                    this.mGoogleAccountSignInDocument = new GoogleAccountSignInDocument(this);
                }
                return this.mGoogleAccountSignInDocument;
            }
        }
        #endregion
        
        #region Fields
        private GoogleAccountSignInDocument mGoogleAccountSignInDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class GoogleAccountSignInDocument : HtmlDocument
    {
        
        public GoogleAccountSignInDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sign in - Google Accounts";
            this.WindowTitles.Add("Sign in - Google Accounts");
            #endregion
        }
        
        #region Properties
        public HtmlEdit EnterYourEmailEdit
        {
            get
            {
                if ((this.mEnterYourEmailEdit == null))
                {
                    this.mEnterYourEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mEnterYourEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mEnterYourEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = " Enter your email";
                    this.mEnterYourEmailEdit.WindowTitles.Add("Sign in - Google Accounts");
                    #endregion
                }
                return this.mEnterYourEmailEdit;
            }
        }
        
        public HtmlInputButton NextButton
        {
            get
            {
                if ((this.mNextButton == null))
                {
                    this.mNextButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mNextButton.SearchProperties[HtmlButton.PropertyNames.Id] = "next";
                    this.mNextButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Next";
                    this.mNextButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mNextButton.WindowTitles.Add("Sign in - Google Accounts");
                    #endregion
                }
                return this.mNextButton;
            }
        }
        
        public HtmlEdit PasswordEdit
        {
            get
            {
                if ((this.mPasswordEdit == null))
                {
                    this.mPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Passwd";
                    this.mPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Passwd";
                    this.mPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mPasswordEdit.WindowTitles.Add("Sign in - Google Accounts");
                    #endregion
                }
                return this.mPasswordEdit;
            }
        }
        
        public HtmlInputButton SignInButton
        {
            get
            {
                if ((this.mSignInButton == null))
                {
                    this.mSignInButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mSignInButton.SearchProperties[HtmlButton.PropertyNames.Id] = "signIn";
                    this.mSignInButton.SearchProperties[HtmlButton.PropertyNames.Name] = "signIn";
                    this.mSignInButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Sign in";
                    this.mSignInButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mSignInButton.WindowTitles.Add("Sign in - Google Accounts");
                    #endregion
                }
                return this.mSignInButton;
            }
        }
        
        public HtmlSpan PasswordErrorMessage
        {
            get
            {
                if ((this.mPasswordErrorMessage == null))
                {
                    this.mPasswordErrorMessage = new HtmlSpan(this);
                    #region Search Criteria
                    this.mPasswordErrorMessage.SearchProperties[HtmlDiv.PropertyNames.Id] = "errormsg_0_Passwd";
                    this.mPasswordErrorMessage.FilterProperties[HtmlDiv.PropertyNames.Class] = "error-msg";
                    this.mPasswordErrorMessage.WindowTitles.Add("Sign in - Google Accounts");
                    #endregion
                }
                return this.mPasswordErrorMessage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mEnterYourEmailEdit;
        
        private HtmlInputButton mNextButton;
        
        private HtmlEdit mPasswordEdit;
        
        private HtmlInputButton mSignInButton;
        
        private HtmlSpan mPasswordErrorMessage;
        #endregion
    }
}
